# Generated by Django 2.2.2 on 2019-06-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_bankaccount_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='credit',
            field=models.IntegerField(default=0),
        ),
    ]
